### ISSUE TITLE
ユーザ情報からQRコード生成

### ISSUE THREAD

**Issue by wamekukyouzin** [kbc-itw/BookChain-Client#19]
ユーザ情報の何をQRコードにするかモデル設計担当と要相談
またそれ用のパッケージと型定義を探すこと

**Comment by Huruikagi** [comment]
@Cyberdrgn 

- [ ] そのライブラリは使いやすそうか？
- [ ] 実際に広く使われているライブラリか？
（npmのダウンロード数、GitHubのスター数などを参照）
- [ ] メンテナンスは行われているか？
（GitHubの最終コミット日などを参照）
- [ ] TypeScriptの型定義ファイルは存在するか？
（DefinitelyTypedの中で検索）
- [ ] package.jsonの依存関係に追加し、プルリクエストを行う

**Comment by wamekukyouzin** [comment]
https://www.npmjs.com/package/qrcode
+ 類似パッケージの中ではよく利用されている
+ 型定義がある
+ 生成したQRCodeをDataURIとして扱える
ことからこれを使うことにした。
